// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbwfdCrpfAQyKsjWslZy3tXRbIAG6988',
    appId: '1:339149818580:web:27dbe92ba6a09b784f4941',
    messagingSenderId: '339149818580',
    projectId: 'bellyrate',
    authDomain: 'bellyrate.firebaseapp.com',
    storageBucket: 'bellyrate.appspot.com',
    measurementId: 'G-FSBC0FFFHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleltBOHKgBgqB7wFx1Mg3TuFzU-Luxto',
    appId: '1:339149818580:android:042cb63b9022a9054f4941',
    messagingSenderId: '339149818580',
    projectId: 'bellyrate',
    storageBucket: 'bellyrate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwffjjymxIGceg5_CPjXmM8pQ7c8Tguk',
    appId: '1:339149818580:ios:4cb238745edb51444f4941',
    messagingSenderId: '339149818580',
    projectId: 'bellyrate',
    storageBucket: 'bellyrate.appspot.com',
    iosClientId: '339149818580-89ki5mv3nf9bjk88cp6v01d4lva5v7ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellyRate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlwffjjymxIGceg5_CPjXmM8pQ7c8Tguk',
    appId: '1:339149818580:ios:4cb238745edb51444f4941',
    messagingSenderId: '339149818580',
    projectId: 'bellyrate',
    storageBucket: 'bellyrate.appspot.com',
    iosClientId: '339149818580-89ki5mv3nf9bjk88cp6v01d4lva5v7ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellyRate',
  );
}
